# background:
#   type: constant
#   c: 2.0

# kernel:
#   mode: separate
#   time_kernel:
#     type: exponential
#     beta: 1.0
#   space_kernel:
#     type: gaussian
#     sigma: .05
#   A:
#     - [0.5, 0.8, 0.7]
#     - [0.0, 0.6, 0.3]
#     - [0.0, 0.0, 0.9]

# simulation:
#   T: 50.0
#   domain: [0, 10, 0, 10]
#   m: 3
#   Lambda: 10.0

# normalization:
#   mean: [5.0, 5.0]
#   cov: [[1.0, 0.0], [0.0, 1.0]]
background:
  type: piecewise
  time_partitions: [0, 5, 10]
  space_partitions:
    - x_min: 0
      x_max: 5
      y_min: 0
      y_max: 10
    - x_min: 5
      x_max: 10
      y_min: 0
      y_max: 10
  # keys must be strings; they can be parsed later into tuples.
  values_dict:
    "(0, 0)": 0.0
    "(0, 1)":
    function: det_intensity
    "(1, 0)": 0.0
    "(1, 1)": 0.0

kernel:
  mode: separate   # 'separate' indicates that time and space kernels are modeled separately.
  time_kernel:
    type: exponential
    beta: 1.0
  space_kernel:
    type: gaussian
    sigma: 1.0
  A:
    - [0.5]       # Branching matrix for a single mark (or event type)

simulation:
  T: 10.0
  domain: [0, 10, 0, 10]   # Spatial domain: [x_min, x_max, y_min, y_max]
  m: 1                    # Number of marks (here 1)
  Lambda: 10.0            # Global upper bound for the thinning algorithm

normalization:
  mean: [5.0, 5.0]
  cov: [[1.0, 0.0], [0.0, 1.0]]

