# sweep.yaml
simulation:
  T: 60             # one sequence per DataFrame
  domain: [0, 10, 0, 10]
  Lambda: 10

background:
  type: constant
  c: 0.8

kernel:
  mode: separate
  time_kernel: 
    type: exponential
    beta: 1.0
  space_kernel: 
    type: gaussian
    sigma: 1.0

normalization: 
  mean: [.0, .0]
  cov: [[1, 0], [0, 1]]

branching_list:                # 12 arbitrary 3×3 examples
  - [[.05, .02, .00], [.00, .05, .02], [.01, .00, .04]]
  - [[.10, .00, .00], [.00, .08, .01], [.00, .00, .06]]
  - [[.05, .05, .05], [.05, .05, .05], [.05, .05, .05]]
  - [[.30, .1, .00], [.00, .30, .01], [.00, .00, .30]]
  - [[.60, .6, .00], [.00, .30, .4], [.00, .00, .70]]

seeds: [0]                     # one seed per run keeps total at 12
